import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Load Nutrient script using Next.js Script component */}
        <Script
          src="/nutrient-viewer.js"
          strategy="beforeInteractive" // Load before the page becomes interactive to reference window.NutrientViewer in the client
        />
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
